name: Main workflow

on:
  pull_request:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: ./build-with.sh docker

      - run: sh -exc 'diff <(sha256sum ./dist/qubes-miragevpn.xen) qubes-miragevpn.sha256 && echo "SHA256 MATCHES" || exit 42'

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: miragevpn.tar.bz2
          path: miragevpn.tar.bz2
